spring:
  application:
    name: Securebase

  sql:
    init:
      mode: never
      data-locations: classpath:db/data.sql

  datasource:
    url: "jdbc:postgresql://localhost:5432/securebase_db"
    username: "admin"
    password: "admin"

  jpa:
    hibernate:
      ddl-auto: update # Options: create, create-drop, update, validate, none
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG